#!/bin/bash

# First checks if Logspitter has been previously installed. If not, exits 0.
if [[ ! -e /usr/bin/logspitter ]]
then
	echo "You don't currently have Logspitter installed. Please run the 'INSTALL' script."
	exit 0
fi

echo "Please drag your log file HERE and press ENTER"
read logfile

if [[ $logfile == *.log ]] ## will read Producer/Procaster logs
then
	echo "Thanks. Processing now..."

	egrep -i '(error)|(fail)|(false)|(rtmp://)|(port)|(\!)\|(drop)|(stamp)|(lost)|(connect)|(connection)|(auth)|(slow)|(check)|(antilag)|(quality)|(suggestion)' $logfile > /tmp/ProducerLogs.filtered.txt && open /tmp/ProducerLogs.filtered.txt

	## Asks if user would like to open original log file for comparison.
	echo "It's still recommended that you view the entire log file -- you may otherwise miss crucial context."
	echo "Would you like to open the full log file? y/n?"
	
	read response

	if [[ $response == "y" ]]
	then
		open $logfile
	else
		exit 0
	fi

elif
	[[ $logfile == *.txt ]] ## will read Studio logs

then
	echo "Thanks. Processing now..."

	egrep -i '(error=203)|(error=301)|error=)|(not\ found)|(rtmp://)|(http_status)|(usage)|(motherboard)|(lost)|(connect)|(connection)|(auth)|(tcp)|(socket)|(deleted)|(network)|(zixi)|(udp)|(antilag)|(code=)' $logfile > /tmp/StudioLogs.filtered.txt | uniq -d -i && open /tmp/StudioLogs.filtered.txt

	echo "It's still recommended that you view the entire log file -- you may otherwise miss crucial context"

	## Asks if user would like to open original log file for comparison.
	echo "Would you like to open the full log file? y/n?"
	read response
	
	if [[ $response == "y" ]] 
	then
		open $logfile

	else
		exit 0
	fi
else
	echo "Oops - not a valid log file. Please use a Studio '.txt' or Producer '.log' file and try again."

fi
