#!/bin/bash

if [[ ! -e /usr/bin/logspitter ]]
then
	echo "You don't currently have Logspitter installed. Please run the 'INSTALL' script."
	exit 0
fi

echo "Please drag your log file HERE and press ENTER"
read logfile

if [[ $logfile == *.log ]]
then
	echo "Thanks. Processing now..."

	egrep -i '(error)|(fail)|(rtmp://)|(port)|(\!)\|(drop)|(stamp)|(lost)|(connect)|(connection)|(auth)|(slow)|(check)|(quality)|(suggestion)' $logfile > /tmp/Logs.txt && open /tmp/Logs.txt

	echo "All done."

elif
	[[ $logfile == *.txt ]]

then
	echo "Thanks. Processing now..."

	egrep -i '(error=203)|(error=301)|(error)|(error=)|(not\ found)|(rtmp://)|(http_status)|(usage)|(motherboard)|(lost)|(connect)|(connection)|(auth)|(tcp)|(socket)|(deleted)|(network)|(zixi)|(udp)|(code=)' $logfile > /tmp/Logs.filtered.txt | uniq -d -i && open -a Sublime\ Text /tmp/Logs.filtered.txt

	echo "All done."
else
	echo "Oops - not a valid log file. Please use a Studio '.txt' or Producer '.log' file and try again."

fi
