#!/bin/bash

## removes logspitter from local bin, then uses sed to replace the ~/.bashrc alias with hashes.
if [[ -e /usr/bin/logspitter || /usr/local/bin/logspitter ]] 
then
	sudo rm /usr/bin/logspitter || /usr/local/bin/logspitter
	sed -e "s/.*logspitter.*/#/g" ~/.bashrc > ~/.bashrc


	echo "The Logspitter tool has been removed from your system."

else
	echo "You don't currently have the Logspitter tool installed on your system."
fi

